### PR TITLE
chore/webpack-eslint-prettier

### PR DESCRIPTION
**Pull request by PaulieScanlon**
- add `webpack.config`
- add `eslint`
- add `prettier`
- add `tsconfig`
- add minimal components from `gatsby-mdx-embed` to test prettier and lint

### CODE REVIEW

**Comment by PaulieScanlon** [comment]
@spences10 @molebox any idea how i add a `husky` `pre-commit` hook to a yarn workspace root? 

Ideally we'd want a `husky` hooks on both the packages.

**Comment by molebox** [comment]
> @spences10 @molebox any idea how i add a `husky` `pre-commit` hook to a yarn workspace root? 
> 
> Ideally we'd want a `husky` hooks on both the packages.

Yeah I've done this before. Lemme check code and get back to you

**Comment by spences10** [comment]
I use Husky like this with `pretty-quick`

```json
"husky": {
  "hooks": {
    "pre-commit": "pretty-quick --staged"
  }
},
```

Don't know how you'd do it in a Yarn workspace tho 🤷‍♀️

Maybe there's something in this [video] about it...

[video]: https://www.youtube.com/watch?v=p6qoJ4apCjA&t=611s

**Comment by PaulieScanlon** [comment]
@spences10 The answer wasn't a fun read but it is in the docs: [nohoist](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/)

Basically by adding...

```javascript
  "workspaces": {
    ...
    "nohoist": [
      "husky"
    ]
  }
```

to the root `package.json` `husky` can run in each package because as the method suggests it's not hoisted.

**Pull request merged**
