### PR TITLE
Add Youtube Nocookie component

### PR DESCRIPTION
**Pull request by spacecowb0y**

### CODE REVIEW

**Comment by spences10** [comment]
Hey @spacecowb0y thanks for the PR, can you give a bit of detail on what this is for please?

My understanding was that the nocookie url was already used in the YouTube component, is this something additional to that?

**Comment by spacecowb0y** [comment]
Hi @spences10 , thank you for your fast reply. As far as I saw the YouTube component use the standard URL when embbeding the video. That's why I implemented a new one pointing to the no-cookie URL.

**Comment by PaulieScanlon** [comment]
@spacecowb0y hey. Thanks for the PR. I wonder if exposing a prop to switch the urls might be a better approach than duplicating the component. If the url is the only difference I'd suggest a useNoCookie optional boolean prop then a condition on the IFrame src url. What do you think?

**Comment by spacecowb0y** [comment]
I thought about that too. Let me re-write it and fix the PR.

**Comment by PaulieScanlon** [comment]
@spacecowb0y Yep! This looks a lot better! Thanks. I'll merge. I think that failing test has been resolved in another PR.

**Pull request merged**
