### PR TITLE
Add security badge

### PR DESCRIPTION
**Pull request by lirantal**
Adding Snyk's security badge that tests for vulnerabilities in open source libraries.

### CODE REVIEW

**Comment by PaulieScanlon** [comment]
Hey @lirantal thanks so much for this! I just replied on Twitter but i'll post here as well.

We currently have x2 packages that might benefit from this:

- mdx-embed: https://snyk.io/test/npm/mdx-embed
- gatsby-plugin-mdx-embed: https://snyk.io/test/npm/gatsby-plugin-mdx-embed

Do you have any thoughts on how to surface which badge related to which package.

...and perhaps in the future we'll have more packages, e.g for Next.js or other frameworks that have plugin eco-systems

**Comment by lirantal** [comment]
Ahh missed the twitter comment! :-)

What if we create a table specific for the security status on the homepage? something like this:

| Package        | Security Status           |
| ------------- |:-------------:|
| mdx-embed      | [Known Vulnerabilities](https://snyk.io/test/npm/mdx-embed) |
| gatsby-plugin-mdx-embed      | [Known Vulnerabilities](https://snyk.io/test/npm/gatsby-plugin-mdx-embed) | 

I can update the PR to reflect that.

**Comment by PaulieScanlon** [comment]
@lirantal oooh this is lovely! yeah that would be brilliant. 

There's one more catch.

In the root of the project there's a [README](https://github.com/PaulieScanlon/mdx-embed) and this is what you see when you visit the project on GitHub

but..

Each of the packages
- [mdx-embed](https://www.npmjs.com/package/mdx-embed) 
- [gatsby-plugin-mdx-embed](https://www.npmjs.com/package/gatsby-plugin-mdx-embed)

...have their own README's located in `packages/...` and this is so as you'll see, the README's aren't empty on npm.

I'm fine with this information being surfaced on the root README so perhaps your PR could add the badges somewhere near where we already have the **npm packages** heading, or maybe the table can include the badges plus links to each of the packages on npm in the table cell?

What do you think?

**Comment by lirantal** [comment]
Ahh indeed, that makes sense. Let me fix the PR for that

**Comment by PaulieScanlon** [comment]
@lirantal That's a work of art! Approved and thank you!

**Pull request merged**
