### PR TITLE
Update twitch iframe title and src so that it doesn't include twitchId when empty.

### PR DESCRIPTION
**Pull request by daisygabi**
I extracted the title and src into variables and constructed their values using the ternary operator.

### CODE REVIEW

**Comment by PaulieScanlon** [comment]
@daisygabi I love it! nice one, thank you!

I just pulled your code and i do have one query and would be keen to get your thoughts.

Both the `channel` and `collection` props are also optional but it doesn't appear to be a problem for the constructed url string if neither are supplied and we don't see `undefined` in the url string which is great, but below you'll see... 

- `Usage` contains `channel=&collection` in the url
- `Channel` contains `&collection=` in the url
- `Collection` contains `&channel=` in the url

Twitch doesn't seem to mind these url params being present even though there are no values assigned to them but do you know if the url still works if these values were omitted in the same way you've handled omitting `&video=` if no `twitchId` is provided?

I'm happy to approve this PR as it stands but i was just curious to know if we should be handling the url construction using a similar method to what you've used to handle the omitted `twitchId` prop if either the `channel` or `collection` weren't provided via props

### Constructed urls: 

#### Usage
```
title: twitch-679474192
url: twitch.tsx:38 https://player.twitch.tv/?autoplay=false&t=0h0m0s&video=v679474192&channel=&collection=&parent=localhost
```

#### Channel
```
title: twitch
url: twitch.tsx:38 https://player.twitch.tv/?autoplay=false&t=0h0m0s&channel=jlengstorf&collection=&parent=localhost
```

#### Collection
```
title: twitch
url twitch.tsx:38 https://player.twitch.tv/?autoplay=false&t=0h0m0s&channel=&collection=DHetedhyqBSVMg&parent=localhost
```

**Comment by daisygabi** [comment]
Good point. I was thinking of later on proposing a builder method to construct the URL knowing more than 1 parameter can be optional. I will test a bit later the weekend how it works with the optional channel and collection. 

I was thinking as well of maybe trying to do a test for this(next week) as well. What do you think?

**Comment by daisygabi** [comment]
I have added a builder method that takes into account the twitchId, collection and channel. The URLs are valid and the videos are shown even if collection or channel is not provided and appended to the Url.

**Comment by PaulieScanlon** [comment]
@daisygabi Hey! i like the helper function but i do have a couple of questions. Would it be possible to convert this to a pure function. I don't think we've used  Classes anywhere else. Also for the same reason i think we're using named exports rather than defaults, and perhaps with the name perhaps if we drop the class it won't need to be called Helper, instead you can export it as named function called `constructTwitchUrl`

**Comment by daisygabi** [comment]
> @daisygabi Hey! i like the helper function but i do have a couple of questions. Would it be possible to convert this to a pure function. I don't think we've used Classes anywhere else. Also for the same reason i think we're using named exports rather than defaults, and perhaps with the name perhaps if we drop the class it won't need to be called Helper, instead you can export it as named function called `constructTwitchUrl`

Hi, got it. The main reason I use classes is that this is how I learned working on fronted, using classes (coming from OOP world), but would definitely change this to function. Thanks for pointing it out.

**Comment by daisygabi** [comment]
I have updated the code, not sure if you want me to keep the `constructTwitchUrl` function where it is now, or if I should move it to `utils/index.ts`.

**Comment by PaulieScanlon** [comment]
@daisygabi Hey, that's perfect. It's fine to leave that function where it is, it's quite specific to Twitch so it makes sense to co-locate this. I think we're good to to merge this in now. Thanks for your effort! great job!

**Comment by daisygabi** [comment]
Thanks for this, it was a pleasure collaborating.

**Comment by PaulieScanlon** [comment]
@daisygabi Hey, yes likewise, i enjoyed collaborating with you too! 

By all means brag about it. I've just released your change in `v0.0.12`, although i did just rename the file to `twitch/utils.ts`, i should have spotted that in the PR, my mistake!

**Pull request merged**
